// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PortInfo {
    /**
     * Creates a new PortInfo instance.
     * @param {Partial<PortInfo>} [$$source = {}] - The source object to create the PortInfo.
     */
    constructor($$source = {}) {
        if (!("Port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Port"] = 0;
        }
        if (!("PID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["PID"] = 0;
        }
        if (!("Process" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Process"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PortInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortInfo(/** @type {Partial<PortInfo>} */($$parsedSource));
    }
}

export class ScriptInfo {
    /**
     * Creates a new ScriptInfo instance.
     * @param {Partial<ScriptInfo>} [$$source = {}] - The source object to create the ScriptInfo.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScriptInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScriptInfo(/** @type {Partial<ScriptInfo>} */($$parsedSource));
    }
}
